name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.214.200.249 << 'EOF'
            cd /home/ubuntu/test
            git pull origin main
            touch test.txt
            echo hi
            cd /home/ubuntu/code/BDOP
            pwd
            /home/ubuntu/.nvm/versions/node/v20.19.1/bin/pm2 stop all
          EOF
